name : CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
    aws-region: us-east-1

  

jobs:
  terraform:
    name: Terraform
    runs-on:  ubuntu-latest
    

    

    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        
  

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1

        with:
          aws-access-key-id:      ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:      ${{ secrets.AWS_SESSION_TOKEN }} 

          aws-region: ${{ env.aws-region }} 

      - name: Terraform Init
        id: init
        run:
          terraform init


      - name: Terraform Destroy
        id: destroy
        run:  terraform destroy -auto-approve
        

      